### ISSUE TITLE
Question: Uploads for nested DataObjects in Frontend Forms

### ISSUE THREAD

**Issue by nicolas-cusan** [lekoala/silverstripe-filepond#10] opened 2022-12-12 17:03 UTC
Hi @lekoala and thank you for this great module!

I am trying to use the field for nested DataObjects in frontend form. As per the SilverStripe docs I use the aray notation to define the sub fields https://docs.silverstripe.org/en/4/developer_guides/forms/how_tos/handle_nested_data/#array-notation and handling the submission on the server "by hand" so save the data on the corresponding objects. The problem is that the upload is not handled correctly for the subobjects, the upload fails on the frontend with a 404 `I can't handle sub-URLs on class SilverStripe\Forms\FormRequestHandler.` error in the console.

Is there by any change a recipe to make this work? I have been at it for a while and so far nothing that I tried has worked (including setting a `setCustomServerConfig` in all kinds of ways).

Happy to prepare a code sample if it helps!

Any help would be greatly appreciated!

Best regards.

**Comment by lekoala** [comment] 2022-12-13 09:28
hi @nicolas-cusan . does it work for regular objects? it looks like an issue with the way silverstripe handles request on form fields, so i'm not sure it's something  than can be fixed at module level but if you have a reproducible example i'm happy to have a look at it

**Comment by nicolas-cusan** [comment] 2022-12-13 10:02
Hi @lekoala thank you for getting back to me. Yes, it works for the fields on the regular form. I will try to put an example together later today.

**Comment by lekoala** [comment] 2023-05-03 10:07
closing this, feel free to reopen if the issue persists

**Closed as completed by lekoala** 2023-05-03 10:07 UTC
